apiVersion: v1
kind: Service
metadata:
  name: express-app-service
spec:
  type: NodePort
  selector:
    app: express-app
  ports:
    - name: http
      nodePort: 30080
      protocol: TCP
      port: 80
      targetPort: 3000
