apiVersion: v1
kind: Service
metadata:
  name: hapi-server-pinpong-svc
spec:
  type: ClusterIP
  selector:
    app: hapi-server-pinpong
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3000
