apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-web-server
  template:
    metadata:
      labels:
        app: basic-web-server
    spec:
      containers:
        - name: basic-web-server
          image: lloydrivers052/basic-web-server:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
