apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: practice # This is the namespace where the deployment is created
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      containers:
        - name: todo-backend
          image: lloydrivers052/todo-backend:v1.0
          ports:
            - containerPort: 3002
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: practice # This is the namespace where the service is created
spec:
  type: ClusterIP
  selector:
    app: backend-deployment
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3002
