apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-ingress
  namespace: practice # This is the namespace where the ingress is created
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: todo-svc
                port:
                  number: 2345
          - path: /todos
            pathType: Prefix
            backend:
              service:
                name: backend-svc
                port:
                  number: 3002
