apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data-pvc # name of the volume claim, this will be used in the deployment
spec:
  storageClassName: shared-data-sc # this is the name you are using later to claim this volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
